# Generated by Django 2.2.6 on 2019-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0004_state_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.AddField(
            model_name='state',
            name='name1',
            field=models.CharField(default=1545, max_length=30),
            preserve_default=False,
        ),
    ]
