# Generated by Django 2.2.6 on 2019-10-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0005_auto_20191019_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name1',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
