# Generated by Django 2.2.6 on 2019-10-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0008_auto_20191020_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techei.State'),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techei.State'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techei.City'),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techei.City'),
        ),
    ]
