# Generated by Django 2.2.6 on 2019-10-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0010_remove_institutionprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techei.State'),
        ),
    ]
