# Generated by Django 2.2.6 on 2019-10-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0011_institutionprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='type',
            field=models.CharField(choices=[('0', 'Student'), ('1', 'Professional'), ('2', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
