# Generated by Django 2.2.6 on 2019-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0012_individualprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
