# Generated by Django 2.2.6 on 2019-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0015_auto_20191022_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festimage',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to='fest/'),
        ),
    ]
