# Generated by Django 2.2.6 on 2019-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0016_auto_20191022_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
