# Generated by Django 2.2.6 on 2019-10-23 15:19

from django.db import migrations, models
import techei.models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0019_auto_20191023_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festclubmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='festimage',
            name='name',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=techei.models.get_file_path),
        ),
    ]
