# Generated by Django 2.2.6 on 2019-10-23 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0020_auto_20191023_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festclubmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
