# Generated by Django 2.2.6 on 2019-10-23 22:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0021_auto_20191023_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festclubmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
