# Generated by Django 2.2.6 on 2019-10-23 22:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0023_auto_20191024_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festclubmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Code'),
        ),
    ]
