# Generated by Django 2.2.6 on 2019-10-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0024_auto_20191024_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='festimage',
            name='user',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='festclubmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
