# Generated by Django 2.2.6 on 2019-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0025_auto_20191024_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='type',
            field=models.CharField(choices=[('0', 'Student'), ('1', 'Professional'), ('2', 'Other')], max_length=20),
        ),
    ]
