# Generated by Django 2.2.6 on 2019-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0026_auto_20191025_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='type',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='attendee_type',
            field=models.IntegerField(choices=[('0', 'Student'), ('1', 'Professional'), ('2', 'Other')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='paylink',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
