# Generated by Django 2.2.6 on 2019-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0028_auto_20191026_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateField(max_length=15),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(max_length=15),
        ),
    ]
