# Generated by Django 2.2.6 on 2019-10-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0029_auto_20191026_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='attendee_type',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Professional'), (2, 'Other')]),
        ),
    ]
