# Generated by Django 2.2.6 on 2019-10-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0031_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techei.InstitutionProfile'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='paylink',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='prize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
