# Generated by Django 2.2.6 on 2019-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0034_applyeventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
