# Generated by Django 2.2.6 on 2019-10-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0035_auto_20191027_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyeventmodel',
            name='event',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='techei.EventModel'),
        ),
        migrations.AlterField(
            model_name='applyeventmodel',
            name='is_confirm',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='applyeventmodel',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
