# Generated by Django 2.2.6 on 2019-10-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0037_seatseventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatseventmodel',
            name='event',
            field=models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='techei.EventModel'),
        ),
        migrations.AlterField(
            model_name='seatseventmodel',
            name='total_seats',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
