# Generated by Django 2.2.6 on 2019-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techei', '0039_auto_20191028_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='paylink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
